### PR TITLE
add user-specified title support

### PR DESCRIPTION
**Pull request by gregschroeder**
this adds support for a user-specified title for the timer, per this request https://www.alfredforum.com/topic/11518-sandwichtimer-%E2%80%94-run-pomodoros-and-other-timers/?do=findComment&comment=68634

the changes are pretty simple.  apologies for the diffs caused by the IDE deciding to adjust the formatting... :/

1) added support for optional argument(s) following the main argument directive (quit, pomodoro, or minutes) to be treated as the timer title
  - this title appears as a disabled first item in the menu, so that the tray doesn't fill with text strings
  - since updating a menu label is not supported, it requires a full replacement of the menu to make changes.  I therefore didn't go too crazy with support for things like editing the value once set.
2) this can be a single or separate arguments, so all of these invocations are identical:
```
  app 1 my title
  app 1 "my title"
  app "1 my title" - the Alfred usage
```
3) uses ID lookup instead of absolute item positioning in menu to toggle start/stop
4) fixed 'stop timer' to work on adhoc timers as well (previously they would still continue)
5) added eslint, fixed accordingly

This is compatible with the existing Alfred workflow, so no changes required there.  (Again, it passes everything as a single argument anyway, so ${1} will now potentially include the title.)

Anyway, thanks for building the tool, and for considering these changes.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for taking the time to work on this!

There are a few things stylistic things I disagree with, but nothing that would prevent merging. I understand and accept your toolchain made some automatic changes to conform to a particular common formatting.

I am slightly bothered by the `eslint` inclusion, because that’s a ton of extra code and I like to keep dependencies to a minimum. Yes, it’s unlikely `eslint` will go away anytime soon, but in addition to it two other tools are included. While I do not mind that you used those to make your changes, I’d rather not force other contributors to use those as well.

However, if you want to update `electron` and `electron-builder` to more recent versions, I’d have no quarrel with that.

> this title appears as a disabled first item in the menu, so that the tray doesn't fill with text strings

I think it would be more useful if the text appeared on the menubar, so you’d know what it refers to without having to click on it, but if you and the user who requested it prefer it this way, I’m fine with it.

> this can be a single or separate arguments, so all of these invocations are identical

`parseArgs()` does bother me. I appreciate you having gone through the trouble of making it so it works in Alfred without changes, but good predictable CLI invocation is important to me. That is to say the main argument and the title should always be two separate arguments (i.e. from the examples, only `app 1 "my title"` is valid; `app 1 my title` would be interpreted as `1 my`; `1 my title` would be invalid, which defaults to pomodoro). I don’t mind changing the Workflow to accommodate that.

Also, I’ve found two bugs in the PR:

We can set a custom title for Pomodoros, but if those show titles at all, they should always be `Work` (or `Pomodoro Work`) and `Break` (or `Pomodoro Break`).

If we set a timer in minutes (I haven’t tried the Pomodoro one yet), when it reaches the end it shows `Pomodoro timer over` on the menubar and `Pomodoro timer done!` on the notification’s title. It should show the timer’s name instead of `Pomodoro` (or just `Timer` if no name was set). Under the current implementation, the menubar says `Timer over` and the notification title is `Timer done!`

**Comment by gregschroeder** [comment]
hopefully you find these changes to your liking.

* removed eslint, its brethren, and directives (+IDE ones) from the code
* tried to restore most formatting changes
* did not knowingly change revs of any dependencies, but it didn't come with a .lock file...
* it is in the menu and not the title because it simply doesn't fit on the tray bar
  * the common use case for supplying titles would be for more than one timer - and then it really gets ridiculous 
  * i didn't see an obvious way to reduce the font size or some other space-saving trick, so on the menu was the best place i could find
* i think the argument treatment is ok
  * i did not want to have to coordinate matching releases of independent products
  * this is backward and forward compatible
  * i would assume that the common use case, by far, is Alfred invocation, which doesn't have the same args/words treatment, so it would just be moving the arg handling problem to a different spot
  * in general, i agree with you about arg handling, but in this case, because invocation is normally via Alfred and not the command line, there isn't the opportunity (or, more importantly, the desire or need) to distinguish `app 1 "my title"` from `app 1 my title` anyway
  * the extra work and especially the headache for users who would then be forced to match different product versions seems extreme relative to the small engineering purity improvement
* custom titles now only work for custom timers, not pomodoro ones
  * simplified code
  * that addressed the notification/done title issue (vestige of supporting manual stop timer on a custom timer which thereafter becomes a pomo timer)

**Comment by vitorgalvao** [comment]
> i think the argument treatment is ok

Please change it for the requested method (separate arguments).

> i did not want to have to coordinate matching releases of independent products

There’s no coordination necessary. It’s a simple change to the Workflow, which itself checks for updates (when invoked) every four days. Even if people update the Workflow before the app, it will keep working as before, there’s no risk.

> this is backward and forward compatible

It’s not forward compatible because we don’t know the future. If an option eventually takes extra arguments (e.g. `quit ID`), having separate arguments from the get go will make this easier.

> i would assume that the common use case, by far, is Alfred invocation, which doesn't have the same args/words treatment, so it would just be moving the arg handling problem to a different spot

And as I said, I prefer to do it that way and don’t mind fixing the Workflow to support it.

> in general, i agree with you about arg handling, but in this case, because invocation is normally via Alfred and not the command line, there isn't the opportunity (or, more importantly, the desire or need) to distinguish `app 1 "my title"` from `app 1 my title` anyway

The Alfred Workflow was created to support the tool, not the reverse. The reason I made it in the first place was because I wanted a timer that could be invoked via the CLI, so getting that right is important.

> the extra work and especially the headache for users who would then be forced to match different product versions seems extreme relative to the small engineering purity improvement

There’s no such problem. Yes, users will need both the App and Workflow to be updated to the latest version instead of just one of them, but if they’re out of sync nothing will break, it will just work as if both were on the older version.

There’s no extra work and no headache. Most users will only know of this change to the app because of the Workflow, so updating the Workflow is a good way to let them know there’s an update, at which point they need only run `:sandwichtimerupdateapp` in Alfred.

**Comment by vitorgalvao** [comment]
I‘ve already made the necessary changes to the Workflow.

**Comment by gregschroeder** [comment]
updated.

**Comment by vitorgalvao** [comment]
Thank you for the fast change. Will make a few quick tests and cut a release probably today.

**Comment by vitorgalvao** [comment]
Release done. Thank you again.

You’re credited on [the release notes](https://github.com/vitorgalvao/sandwichtimer/releases/tag/1.1.0) and [the forum post](https://www.alfredforum.com/topic/11518-sandwichtimer-%E2%80%94-run-pomodoros-and-other-timers/?tab=comments#comment-76535). If you have a forum handle or would like me to write your name in another way (not the Github handle), please let me know and I’ll edit it.

**Pull request merged**
